### ISSUE TITLE
Hacktoberfest 2022

### ISSUE THREAD

**Issue by arthurits** [arthurits/ErgoLux#1]
# This repo is participating in Hacktoberfest 2022! #
Translations are welcome as a way to enter Hacktoberfest 2022.

## Contributions ##
We are looking for contributions to translate this project's string resources ([strings.resx](https://github.com/arthurits/ErgoLux/blob/master/ErgoLux/localization/strings.resx), 186 strings) into any of the [24 official languages in the EU](https://european-union.europa.eu/principles-countries-history/languages_en#:~:text=The%20EU%20has%2024%20official,%2C%20Slovenian%2C%20Spanish%20and%20Swedish.):
- Bulgarian
- Croatian
- ~~Czech~~
- ~~Danish~~
- Dutch (both ~~`nl-BE`~~ and `nl-NL`)
- ~~English~~
- Estonian
- Finnish
- ~~French~~
- ~~German~~
- Greek
- Hungarian
- Irish
- ~~Italian~~
- Latvian
- Lithuanian
- Maltese
- Polish
- Portuguese (both `pt-PT` and `pt-BR`)
- Romanian
- ~~Slovak~~
- Slovenian
- ~~Spanish~~
- Swedish

Other languages might be accepted (but not granted) upon personal consideration.

Please note that <kbd><img title="Bangla" alt="Bangla" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/bd.svg" width="22"></kbd>Bangla (bn-BD), <kbd><img title="Czech" alt="Czech" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/cz.svg" width="22"></kbd> Czech, <kbd><img title="Danish" alt="Danish" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/dk.svg" width="22"></kbd>Danish (da-DK), <kbd><img title="Dutch" alt="Dutch" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/be.svg" width="22"></kbd> Belgium Dutch (nl-BE), <kbd><img title="English" alt="English" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/gb.svg" width="22"></kbd>English, <kbd><img title="French" alt="French" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/fr.svg" width="22"></kbd>French, <kbd><img title="German" alt="German" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/de.svg" width="22"></kbd>German, <kbd><img title="Italian" alt="Italian" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/it.svg" width="22"></kbd>Italian, <kbd><img title="Russia" alt="Russia" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/ru.svg" width="22"></kbd>Russian, <kbd><img title="Slovak" alt="Slovak" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/sk.svg" width="22"></kbd>Slovak, <kbd><img title="Spanish" alt="Spanish" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/es.svg" width="22"></kbd> Spanish, <kbd><img title="Turkey" alt="Turkey" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/tr.svg" width="22"></kbd> Turkish (tr-TR), and <kbd><img title="Chinese" alt="Chinese" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/cn.svg" width="22"></kbd> Simplified Chinese (zh-Hans)  are already covered.

## Instructions ##
Create a new PR  by adding a new file in the [project's localization folder](https://github.com/arthurits/ErgoLux/tree/master/ErgoLux/localization) named `strings.xx-XX.resx`, where xx-XX stands for the chosen language; i.e.: `de-DE` for German, `fr-FR` for French, et cetera. The new file should contain all the string resources from the base [strings.resx](https://github.com/arthurits/ErgoLux/blob/master/ErgoLux/localization/strings.resx) translated into the chosen language.

Some of the string resources include string formatters and other characters (ampersands, line breaks, et cetera) that should be respected in order for the PR to be accepted.

## Approval ##
Please wait until your PR is reviewed, validated, merged and labelled with `hacktoberfest-accepted` before it is recognised in your [Hacktoberfest profile](https://hacktoberfest.com/).

**Comment by SvA1** [comment]
I could help you out with the German translation.

**Comment by Xav83** [comment]
Hi @arthurits,

I have created a created a Pull Request regarding the french translation (PR #4), and, on my Hacktoberfest profile, this Pull Request has been tagged as `NOT-PARTICIPATING`.

![Screenshot from 2022-10-03 21-51-39](https://user-images.githubusercontent.com/6787157/193667169-e7de7635-a46d-43f4-807b-f2a6f5f55655.png)

**Comment by arthurits** [comment]
> I have created a created a Pull Request regarding the french translation (PR #4), and, on my Hacktoberfest profile, this Pull Request has been tagged as `NOT-PARTICIPATING`.

Hi @Xav83,
I believe contributors have to wait untill the PR is merged, approved, and tagged as accepted.

I've just reviewed your PR and all should be right in a short period of time. Should there be any problems regarding this issue, please don't hesitate to let me know.

Merci beaucoup pour votre contribution!

**Comment by arthurits** [comment]
> I could help you out with the German translation.

I'm really happy for your contribution. Vielen Dank!

**Comment by sarequl** [comment]
Can I translate this to Bangla (Bn)?

**Comment by arthurits** [comment]
> Can I translate this to Bangla (Bn)?

Hi @sarequl!

Sure! I would rather prefer Hindi but Bangla is also all right. Please keep in mind [what I told you previoulsy](https://github.com/arthurits/SignalAnalysis/issues/1#issuecomment-1266699113).
Many of the strings in both projects are the same, so this will make your work easier (keep in mind that both translations should be consistent).

Thanks so much for your interest!

**Comment by fadkeabhi** [comment]
May I work on hindi translations

**Comment by arthurits** [comment]
> May I work on hindi translations

Sure! I would be very glad if you could! 🙂

**Comment by Pyr0x1** [comment]
Hello, I can work on the italian translation if not taken yet

**Comment by arthurits** [comment]
Hi @Pyr0x1, nobody is working on the Italian translation.

**Comment by fadkeabhi** [comment]
> 

I am done with hindi translations. ans made a PR here https://github.com/arthurits/SignalAnalysis/pull/6 . please approve with hacktoberfest-accepted label.

**Comment by Pyr0x1** [comment]
One note, the PRs aren't recognized as participating in Hacktoberfest (unless you mark them with the `hacktoberfest-accepted` label), I think the label linked to the project must be `hacktoberfest` and not `hacktoberfest-2022` to make PRs automatically detected as partecipating.

**Comment by arthurits** [comment]
> One note, the PRs aren't recognized as participating in Hacktoberfest (unless you mark them with the `hacktoberfest-accepted` label)

That's true. I believe the idea is that only approved and merged PRs, which are labelled as `hacktoberfest-accepted`, do participate in Hacktoberfest. But that's not automatic, since maintainers have to validate PRs to check whether they qualify for Hacktoberfest or not. So, unless mistaken, that label is the last step in the process and has to be added by the maintainer. 

>I think the label linked to the project must be `hacktoberfest` and not `hacktoberfest-2022` to make PRs automatically detected as partecipating.

That's a good point, so I've just added that label at the project level to avoid any unexpected issues. However, after reading the [Hacktoberfest validation guide](https://hacktoberfest.com/participation/#pr-mr-details) I don't believe there's any automatic detection, unless PRs are merged and labelled as `hacktoberfest-accepted`.

Please let me know if there's any misunderstanding on my side. Also, don't hesitate to let me know if any of your two contributions ([here](https://github.com/arthurits/ErgoLux/pull/7) and [here](https://github.com/arthurits/SignalAnalysis/pull/7)) aren't recognised correctly.

I really appreciate your positive feedback!

**Comment by Pyr0x1** [comment]
> > One note, the PRs aren't recognized as participating in Hacktoberfest (unless you mark them with the `hacktoberfest-accepted` label)
> 
> That's true. I believe the idea is that only approved and merged PRs, which are labelled as `hacktoberfest-accepted`, do participate in Hacktoberfest. But that's not automatic, since maintainers have to validate PRs to check whether they qualify for Hacktoberfest or not. So, unless mistaken, that label is the last step in the process and has to be added by the maintainer.
> 
> > I think the label linked to the project must be `hacktoberfest` and not `hacktoberfest-2022` to make PRs automatically detected as partecipating.
> 
> That's a good point, so I've just added that label at the project level to avoid any unexpected issues. However, after reading the [Hacktoberfest validation guide](https://hacktoberfest.com/participation/#pr-mr-details) I don't believe there's any automatic detection, unless PRs are merged and labelled as `hacktoberfest-accepted`.
> 
> Please let me know if there's any misunderstanding on my side. Also, don't hesitate to let me know if any of your two contributions ([here](https://github.com/arthurits/ErgoLux/pull/7) and [here](https://github.com/arthurits/SignalAnalysis/pull/7)) aren't recognised correctly.
> 
> I really appreciate your positive feedback!

No problem 😁 the PR were recognized correctly, thank you
