### ISSUE TITLE
Russian translation (Hacktoberfest 2022)

### ISSUE THREAD

**Issue by arthurits** [arthurits/ErgoLux#10]
# This repo is participating in Hacktoberfest 2022! #
We are looking for contributions to translate this project's string resources ([strings.resx](https://github.com/arthurits/ErgoLux/blob/master/ErgoLux/localization/strings.resx), 185 strings) into Russian.

## Instructions ##
Create a new PR by adding a new file in the [project's localization folder](https://github.com/arthurits/ErgoLux/tree/master/ErgoLux/localization) named `strings.ru-RU.resx`. The new file should contain all the string resources from the base [strings.resx](https://github.com/arthurits/ErgoLux/blob/master/ErgoLux/localization/strings.resx) translated into Russian.

Some of the string resources include string formatters and other characters (ampersands, line breaks, et cetera) that should be respected in order for the PR to be accepted.

### Approval ###
Please wait until your PR is reviewed, validated, merged and labelled with `hacktoberfest-accepted` before it is recognised in your [Hacktoberfest profile](https://hacktoberfest.com/).

**Comment by theadityaagnihotri** [comment]
can i work on this?

**Comment by arthurits** [comment]
Hi @theadityaagnihotri!
If you are conversant with Russian and its usage in software programs, you can give it a try.
