### ISSUE TITLE
Russian (ru-RU) translation needed

### ISSUE THREAD

**Issue by arthurits** [arthurits/ErgoLux#27]
This application is currently available in 13 languages:

- Bangla (bn-BD) <kbd><img title="Bangla" alt="Bangla" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/bd.svg" width="22"></kbd>
- Belgium Dutch (nl-BE)<kbd><img title="Dutch" alt="Dutch" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/be.svg" width="22"></kbd>
- Czech (cs-CZ) <kbd><img title="Czech" alt="Czech" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/cz.svg" width="22"></kbd>
- Danish (da-DK) <kbd><img title="Danish" alt="Danish" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/dk.svg" width="22"></kbd>
- German (de-DE) <kbd><img title="German" alt="German" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/de.svg" width="22"></kbd>
- English (en) <kbd><img title="English" alt="English" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/gb.svg" width="22"></kbd>
- French (fr-FR)<kbd><img title="French" alt="French" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/fr.svg" width="22"></kbd>
- Italian (it-IT) <kbd><img title="Italian" alt="Italian" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/it.svg" width="22"></kbd>
- Japanese (ja-JP). <kbd><img title="Japanese" alt="Japanese" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/jp.svg" width="22"></kbd>
- Lithuanian (lt-LT) <kbd><img title="Lithuanian" alt="Lithuanian" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/lt.svg" width="22"></kbd>
- Slovak (sk-SK) <kbd><img title="Slovak" alt="Slovak" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/sk.svg" width="22"></kbd>
- Spanish (es) <kbd><img title="Spanish" alt="Spanish" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/es.svg" width="22"></kbd>
- Simplified Chinese (zh-Hans) <kbd><img title="Chinese" alt="Chinese" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/cn.svg" width="22"></kbd>

There are a total of 201 strings that need to be translated into Russian (ru-RU). <kbd><img title="Russia" alt="Russia" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/ru.svg" width="22"></kbd>

## Instructions ##
There are several ways to contribute the translation. However, all of them should be done via PR along with one of the following three options:

- Edit this [Excel book](https://github.com/arthurits/ErgoLux/blob/master/ErgoLux/localization/Russian%20(ru-RU)%20translation.xlsx) and add the translated strings to the table.
- Add a new file in the [project's localization folder](https://github.com/arthurits/ErgoLux/blob/master/ErgoLux/localization) named `strings.ru-RU.resx`. The new file should contain all the string resources from the base [strings.resx](https://github.com/arthurits/ErgoLux/blob/master/ErgoLux/localization/strings.resx) translated into Russian.
Some of the string resources include string formatters and other characters (ampersands, line breaks, et cetera) that should be respected in order for the PR to be accepted.
If you use VS along with the extension [ResX Manager](https://github.com/dotnet/ResXResourceManager) you can translate the strings without manually editing the resx file, since the this extension automatically updates the corresponding `strings.xx-YY.resx` files.
- Any other option that you are comfortable with.

Please, don't hesitate to ask if some strings need contextualization for their translation.

**Comment by shmudivel** [comment]
Hi, I am a professional translator (EN-RU-CN). 
This is my first contribution, and I would like to offer my help. 
Please let me know if I made any errors in my pull request. 
Thank you.

**Comment by arthurits** [comment]
Hi @shmudivel!

Thanks so much for your help. As far as I can see, there's no pull request nor any contribution on the repo from your side. Apart from forking this repo (you already did this), you need to create and push a new branch with the strings translation (either in the Excel file or the `strings.ru-RU.resx` file, which ever option you feel more comfortable with).

**Comment by arthurits** [comment]
Thanks for your help @shmudivel!

I've realized that string `strMsgBoxTaskCancel` remains untranslated. It's a message shown to the used whenever he cancels some CPU-intensive calculation. The English text is:

_Computation of the Hausdorff-Besicovitch fractal
dimension has been stopped._

This is my attempt to get the equivalent Russian expression:

_Вычисление фрактала Хаусдорфа-Безиковича
измерение было остановлено._

Any suggestions?

**Comment by arthurits** [comment]
@shmudivel,

There's another project that would benefit from your help. The strings are already translated into Russian, but the newest ones (around 37 of them) are still pending. I'd be really grateful if you could have a look at them, both the missing ones and the already translated.

In case you are interested, please have a look [here](https://github.com/arthurits/SignalAnalysis/issues/21).

**Comment by shmudivel** [comment]
Hi @arthurits 

strMsgBoxTaskCancel is missing in my copy, how to added it? just click "+ Add"?
<img width="576" alt="Screenshot 2023-04-05 at 09 45 26" src="https://user-images.githubusercontent.com/82043832/230148769-cf886efd-6ad4-48bb-9f99-5973475372e6.png">
<img width="576" alt="Screenshot 2023-04-05 at 09 45 26" src="https://user-images.githubusercontent.com/82043832/230148790-36736bdb-7cc0-40e8-b3c5-0889c4523194.png">

**Comment by shmudivel** [comment]
> @shmudivel,
> 
> There's another project that would benefit from your help. The strings are already translated into Russian, but the newest ones (around 37 of them) are still pending. I'd be really grateful if you could have a look at them, both the missing ones and the already translated.
> 
> In case you are interested, please have a look [here](https://github.com/arthurits/SignalAnalysis/issues/21).

Yes, I'll be glad to help more.
Should I open an issue, or should I just fork it and see the missing translation locally?

**Comment by arthurits** [comment]
> strMsgBoxTaskCancel is missing in my copy, how to added it? just click "+ Add"?
> 
> This more correct -> English: Computation of the Hausdorff-Besicovitch fractal dimension has been stopped.
> 
> Russian: Вычисление фрактальной размерности Хаусдорфа-Безиковича было остановлено.

My bad, there was no key named `strMsgBoxTaskCancel`. I've just added it along with your suggested translation. My appologies.

In order to see the latest changes, you'll need to update your branch, which currently is missing the most recent updates.
![image](https://user-images.githubusercontent.com/63915486/230300956-e5d028b7-9c97-4498-a027-78b224677e94.png)

**Comment by shmudivel** [comment]
> > strMsgBoxTaskCancel is missing in my copy, how to added it? just click "+ Add"?
> > This more correct -> English: Computation of the Hausdorff-Besicovitch fractal dimension has been stopped.
> > Russian: Вычисление фрактальной размерности Хаусдорфа-Безиковича было остановлено.
> 
> My bad, there was no key named `strMsgBoxTaskCancel`. I've just added it along with your suggested translation. My appologies.
> 
> In order to see the latest changes, you'll need to update your branch, which currently is missing the most recent updates. ![image](https://user-images.githubusercontent.com/63915486/230300956-e5d028b7-9c97-4498-a027-78b224677e94.png)

Hi, @arthurits 
I think I did something wrong with update
Could you help with this, how to fix 
"This branch is [2 commits ahead](https://github.com/shmudivel/ErgoLux/compare/arthurits:ErgoLux:master...master) of arthurits:master."
I haven't changed anything, I just did something wrong when I tried to update my branch and repository. Sorry.
<img width="997" alt="Screenshot 2023-04-07 at 11 24 43" src="https://user-images.githubusercontent.com/82043832/230665798-d580b2bf-c214-4678-8593-6d0de07e0b07.png">

**Comment by shmudivel** [comment]
> > Yes, I'll be glad to help more. Should I open an issue, or should I just fork it and see the missing translation locally?
> 
> Great! Thanks in advance!
> 
> You can use whatever procedure you feel most confortable with. Personally, I use VS and the [ResX extension](https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager), which simplifies a lot the translation and handling of the string resources. For me it's a no brainer, and it's way better than directly editing the `resx` files.
> 
> I've created this [Excel book](https://github.com/arthurits/SignalAnalysis/blob/master/SignalAnalysis/localization/Russian%20(ru-RU)%20translation.xlsx) with the keys, English names, and the corresponding Russian translations, in case you prefer it better. Just create a PR and add the missing string translations to the table in the book. I'll then update the corresponding resource file using ResX (no problem on my side).
> 
> I'll gladly provide context and screenshots whenever needed.
> 
> In the end, I'm fine adapting to whatever procedure works best for you, so don't worry about that!

Ok, I'll do as I did previously with ErgoLux. (Sunday or Monday)

**Comment by arthurits** [comment]
Nice. No need to hurry. Just take it easy.
