### ISSUE TITLE
Translations and reviews

### ISSUE THREAD

**Issue by arthurits** [arthurits/ErgoLux#40]
# This repo is participating in Hacktoberfest 2023! #
Missing translations and reviews are welcome as a way to enter Hacktoberfest 2023.

## Languages and cultures ##

This application is currently available in 16 languages. However, since the addition of new string resources to the application, these cultures's resources need to be updated, as well as reviewing, and fine tunning:

- Bangla (bn-BD) <kbd><img title="Bangla" alt="Bangla" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/bd.svg" width="22"></kbd>
- Belgium Dutch (nl-BE)<kbd><img title="Dutch" alt="Dutch" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/be.svg" width="22"></kbd>
- Czech (cs-CZ) <kbd><img title="Czech" alt="Czech" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/cz.svg" width="22"></kbd>
- Danish (da-DK) <kbd><img title="Danish" alt="Danish" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/dk.svg" width="22"></kbd>
- German (de-DE) <kbd><img title="German" alt="German" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/de.svg" width="22"></kbd>
- English (en) <kbd><img title="English" alt="English" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/gb.svg" width="22"></kbd>
- French (fr-FR)<kbd><img title="French" alt="French" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/fr.svg" width="22"></kbd>
- Hungarian (hu-HU) <kbd><img title="Hungarian" alt="Hungarian" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/hu.svg" width="22"></kbd>
- Italian (it-IT) <kbd><img title="Italian" alt="Italian" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/it.svg" width="22"></kbd>
- Japanese (ja-JP). <kbd><img title="Japanese" alt="Japanese" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/jp.svg" width="22"></kbd>
- Lithuanian (lt-LT) <kbd><img title="Lithuanian" alt="Lithuanian" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/lt.svg" width="22"></kbd>
- Russian (ru-RU) <kbd><img title="Russia" alt="Russia" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/ru.svg" width="22"></kbd>
- Slovak (sk-SK) <kbd><img title="Slovak" alt="Slovak" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/sk.svg" width="22"></kbd>
- Spanish (es) <kbd><img title="Spanish" alt="Spanish" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/es.svg" width="22"></kbd>
- Turkish (tr-TR) <kbd><img title="Turkey" alt="Turkey" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/tr.svg" width="22"></kbd>
- Simplified Chinese (zh-Hans) <kbd><img title="Chinese" alt="Chinese" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/cn.svg" width="22"></kbd>

## Instructions ##

There are several ways to contribute the translations. However, all of them should be done via PR and one of the following options:
- If you use VS along with the extension [ResX Manager](https://github.com/dotnet/ResXResourceManager) you can translate the strings without manually editing the resx file, since this extension automatically updates the corresponding `strings.xx-YY.resx` files. This is the easiest and most practical way.
- Edit this [Excel book](https://github.com/arthurits/ErgoLux/blob/master/ErgoLux/localization/Strings.xlsx) and add the missing (empty cells) translations to the corresponding column (culture) in the table. Please, mark all cells that have been modified, so that I can later update the corresponding `strings.xx-YY.resx` file.
- Any other option that you are comfortable with.

Some of the string resources include string formatters and other characters (ampersands, line breaks, et cetera) that should be respected in order for the PR to be accepted. Please, don't hesitate to ask in case some strings need contextualization (or screenshots) for their proper translation.

## Approval ##
Please wait until your PR is reviewed, validated, merged and labelled with `hacktoberfest-accepted` before it is recognised in your [Hacktoberfest profile](https://hacktoberfest.com/).

**Comment by yashthipsay** [comment]
Hi @arthurits, thanks for the opportunity. I would like to take up this issue for Hacktoberfest 2023! 
How many emtpy cells need to filled before a valid pull request?

**Comment by arthurits** [comment]
Hi @yashthipsay,

Thanks for your interest. It really depends on the language/culture. The best way to know that is by downloading the Excel book  referenced in this issue description and filter the corresponding column to see how many string translations are missing for a given language. I expect the maximum to be around 40 strings.

What I'm looking for is quality and precision in the translations. So, besides completing any of the above languages/cultures, I'd also like native speakers to review the already translated strings so that they don't feel awkward. I'm willing to provide any kind of needed context and help to achieve proper translations.

If, however, you are looking to contribute a new language/culture (besides the already 15 ones in the above description), the total number of strings to translate is around 200.

Looking forward to your contribution!
