### ISSUE TITLE
Chinese translation (Hacktoberfest 2022)

### ISSUE THREAD

**Issue by arthurits** [arthurits/ErgoLux#8]
# This repo is participating in Hacktoberfest 2022! #
We are looking for contributions to translate this project's string resources ([strings.resx](https://github.com/arthurits/ErgoLux/blob/master/ErgoLux/localization/strings.resx), 201 strings) into Chinese.
I'm not conversant with Chinese and its variants, so the most widely used in software applications are preferred (these might be `zh-CN`, `zh-Hant`, `zh-Hans`).

## Instructions ##
Create a new PR by adding a new file in the [project's localization folder](https://github.com/arthurits/ErgoLux/tree/master/ErgoLux/localization) named `strings.xx-XX.resx` (where `xx-XX` stands for the Chinese variant chosen). The new file should contain all the string resources from the base [strings.resx](https://github.com/arthurits/ErgoLux/blob/master/ErgoLux/localization/strings.resx) translated into Chinese.

Some of the string resources include string formatters and other characters (ampersands, line breaks, et cetera) that should be respected in order for the PR to be accepted.

### Approval ###
Please wait until your PR is reviewed, validated, merged and labelled with `hacktoberfest-accepted` before it is recognised in your [Hacktoberfest profile](https://hacktoberfest.com/).

**Comment by arthurits** [comment]
Thanks @myd7349!

This issue is closed by PR #30.

**Comment by myd7349** [comment]
It's my pleasure. @arthurits
Please feel free to reach out to me if there are new words that need to be translated.

BTW, I am unable to provide assistance with Traditional Chinese translation. There are differences in vocabulary and sentence structure between simplified and traditional Chinese. While most people from mainland China may be able to struggle through reading traditional Chinese, they would not be able to write it proficiently.

**Comment by arthurits** [comment]
Thanks so much for your kindness and interest @myd7349.

For the time being, I'm more than happy with Simplified Chinese, since it targets the largest number of potential users. Should there be any request for Traditional Chinese, I'll then look for further help for the translation.
